### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by zhuqiangLu** [kentechx/pointnext#3]
Hi and thank you for your work.

Have you tested your implementation on the benchmarks/datasets mentioned in the paper?

**Comment by kentechx** [comment]
Here are some performance tests:
- [ModelNet40](https://github.com/kentechx/modelnet40_experiments?tab=readme-ov-file#results): OA 91.3%
- [S3DIS](https://github.com/kentechx/s3dis_sem_experiments?tab=readme-ov-file#results)
  ![image](https://github.com/kentechx/pointnext/assets/26745565/d90f7af1-0f69-4307-9aee-9a6c690c06e4)

**Comment by zhuqiangLu** [comment]
Ahh I see, thank you for your quick response. 

Closing this issue.
